POST http://127.0.0.1:8000/operation
Content-Type: application/json

{
  "description": "string",
  "negative": "string"
}

###

GET http://127.0.0.1:8000/operation/1
Accept: application/json

###

GET http://127.0.0.1:8000/operation?page=&size=&description=&debit=
Accept: application/json

###
