version: "3.9"

services:
  api:
    build:
      context: .
      dockerfile: build/docker/Dockerfile
      args:
        app: api
    env_file:
      - .env
    ports:
      - "8000:8000"
    healthcheck:
      test: nc -z localhost 8000 || exit -1
      interval: 10s
      timeout: 5s
      retries: 3
    depends_on:
      database:
        condition: service_healthy
  database:
    image: "postgres:14-alpine3.15"
    env_file:
      - .env
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 3
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${APP_DB_USER}
      POSTGRES_PASSWORD: ${APP_DB_PASS}
      POSTGRES_DB: ${APP_DB_NAME}